Homework1-needs-some-refactoring
Marji9988/ExadelSandbox2022 pull request #1
Opened 2022-03-04 11:13 UTC by Marji9988

2022-03-04 11:20 UTC, Marji9988 commented
Would love all the feedback/remarks I can get.

2022-03-04 16:41 UTC, AudriusBaltusis requested changes

2022-03-04 16:41 UTC, AudriusBaltusis commented on routes/userAccount.js
> +router.route('/income')
This and following routes are not related to `userAccount`. You should use more generic module name, or split to different modules

2022-03-04 16:41 UTC, AudriusBaltusis commented on controllers/user.js
> +const createNewIncome = (req, res) => {
This and some other methods are not related to `user` and should be moved to another module

2022-03-04 16:41 UTC, AudriusBaltusis commented on controllers/user.js
> +  // eslint-disable-next-line max-len
Please adjust your `eslint` settings and reformat code

2022-03-04 16:41 UTC, AudriusBaltusis commented on controllers/user.js
> +// making all the expenses 0. (will be refactored for sure!)
Please remove unused methods instead of commenting out

2022-03-04 16:41 UTC, AudriusBaltusis commented on controllers/user.js
> +// Creates new account for the user with name, currency, balance and id.
Minor: such comments are redundant, method name is self-explanatory

2022-03-09 07:56 UTC, AudriusBaltusis commented
Any updates on this?

2022-03-09 08:12 UTC, Marji9988 commented
> Any updates on this?

Hello Audrius. The changes you've requested will be done today in a new pull request, along with the new homework.

2022-03-14 05:47 UTC, closed without merging